import type { Metadata } from "next";
import "./globals.css";
import { helvneue } from "./font";
import { HeroUIProvider } from "@heroui/system";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <HeroUIProvider>
      <html lang="en">
        <body className={` ${helvneue.className}  antialiased`}>
          {children}
        </body>
      </html>
    </HeroUIProvider>
  );
}
