const industries = [
  "Accounting",
  "Actuary",
  "Agriculture",
  "Airlines/Aviation/Aerospace",
  "Alternative Capital",
  "Alternative Dispute Resolution",
  "Alternative Medicine",
  "Animation",
  "Apparel & Fashion",
  "Architecture & Planning",
  "Arts and Crafts",
  "Automotive",
  "Aviation & Aerospace",
  "Banking",
  "Beauty",
  "Biotechnology",
  "Broadcast Media",
  "Stock Broking",
  "Building Materials",
  "Business Supplies and Equipment",
  "Capital Markets",
  "Captives",
  "Chemicals",
  "Civic & Social Organisation",
  "Civil Engineering",
  "Claims",
  "Climate",
  "Commercial Real Estate",
  "Computer & Network Security",
  "Computer Games",
  "Computer Hardware",
  "Computer Networking",
  "Computer Software",
  "Construction",
  "Consulting",
  "Consumer Electronics",
  "Consumer Goods",
  "Consumer Services",
  "Cosmetics",
  "Cyber",
  "Dairy",
  "Defense & Space",
  "Design",
  "Directors & Officers",
  "E-Learning",
  "Education Management",
  "Electrical/Electronic Manufacturing",
  "Emerging Markets",
  "Emerging Risks",
  "Entertainment",
  "Environmental Services",
  "Events Services",
  "ESG",
  "Executive Office",
  "Fashion",
  "Facilities Services",
  "Farming",
  "Financial Lines",
  "Financial Services",
  "Fine Art",
  "Fishery",
  "Food & Beverages",
  "Food Production",
  "Fund-Raising",
  "Furniture",
  "Gambling & Casinos",
  "Glass, Ceramics & Concrete",
  "Government Administration",
  "Government Relations",
  "Graphic Design",
  "Health, Wellness and Fitness",
  "Higher Education",
  "Hospital & Health Care",
  "Hospitality",
  "Human Resources",
  "Social Worker",
  "Import and Export",
  "Individual & Family Services",
  "Industrial Automation",
  "Information Services",
  "Information Technology and Services",
  "Insurance",
  "International Affairs",
  "International Trade and Development",
  "Internet",
  "Investment Banking",
  "Investment Management",
  "Judiciary",
  "Kidnap & Ransom",
  "Law",
  "Leisure Travel & Tourism",
  "Liability",
  "Libraries",
  "Logistics and Supply Chain",
  "Luxury Goods & Jewelry",
  "Machinery",
  "Management Consulting",
  "Marine Cargo",
  "Marine Hull",
  "Maritime",
  "Market Research",
  "Marketing and Advertising",
  "Engineering",
  "Media Production",
  "Medical Devices",
  "Medical Practice",
  "Mental Health Care",
  "Military",
  "Mining",
  "Mining & Metals",
  "Motion Pictures and Film",
  "Museums and Institutions",
  "Music",
  "Nanotechnology",
  "Newspapers",
  "Nonprofit Organisation Management",
  "Offshore Energy",
  "Oil & Energy",
  "Online Media",
  "Onshore Energy",
  "Operations",
  "Outsourcing/Offshoring",
  "Package/Freight Delivery",
  "Packaging and Containers",
  "Paper & Forest Products",
  "Parametrics",
  "Performing Arts",
  "Pharmaceuticals",
  "Philanthropy",
  "Photography",
  "Plastics",
  "Political Organisation",
  "Politics",
  "Primary/Secondary Education",
  "Printing",
  "Product Recall",
  "Professional Indemnity (E&O)",
  "Professional Training & Coaching",
  "Programme Development",
  "Property",
  "Public Policy",
  "Public Relations and Communications",
  "Public Safety",
  "Publishing",
  "Railroad Manufacture",
  "Ranching",
  "Real Estate",
  "Recreational Facilities and Services",
  "Reinsurance",
  "Religious Institutions",
  "Renewables & Environment",
  "Research",
  "Restaurants",
  "Retail",
  "Security and Investigations",
  "Semiconductors",
  "Student",
  "Shipbuilding",
  "STEM",
  "Sporting Goods",
  "Sports",
  "Staffing and Recruiting",
  "Supermarkets",
  "Telecommunications",
  "Teacher",
  "Textiles",
  "Think Tanks",
  "Tobacco",
  "Translation and Localisation",
  "Transportation/Trucking/Railroad",
  "Underwriting",
  "Utilities",
  "Venture Capital & Private Equity",
  "Veterinary",
  "Warehousing",
  "Wholesale",
  "Wine and Spirits",
  "Writing and Editing",
  "Other",
];

export default industries;
