const skills = [
  "Strategic Planning",
  "Business Development",
  "Change Management",
  "Operations Management",
  "Project Management",
  "Program Management",
  "Budgeting & Forecasting",
  "Business Strategy",
  "Risk Management",
  "Mergers & Acquisitions",
  "Stakeholder Management",
  "Supply Chain Management",
  "Corporate Governance",
  "Agile Leadership",
  "OKRs/KPIs Management",
  "Lean Management",
  "Six Sigma",
  "Crisis Management",
  "Team Building",
  "Performance Management",
  "Public Speaking",
  "Written Communication",
  "Cross-Cultural Communication",
  "Negotiation",
  "Conflict Resolution",
  "Emotional Intelligence",
  "Storytelling",
  "Active Listening",
  "Coaching & Mentoring",
  "Facilitation",
  "Empathy",
  "Interpersonal Skills",
  "Time Management",
  "Adaptability",
  "Collaboration",
  "Software Development",
  "Web Development",
  "Cloud Computing (AWS, Azure, GCP)",
  "Cybersecurity",
  "Network Administration",
  "IT Infrastructure",
  "DevOps",
  "Artificial Intelligence (AI)",
  "Machine Learning",
  "Data Engineering",
  "Database Management (SQL, NoSQL)",
  "Blockchain",
  "Internet of Things (IoT)",
  "API Integration",
  "Mobile Development (iOS, Android)",
  "AR/VR Development",
  "Data Analysis",
  "Business Intelligence (BI)",
  "Data Visualization (Tableau, Power BI)",
  "Excel (Advanced)",
  "SQL",
  "Python for Data Science",
  "R Programming",
  "Predictive Analytics",
  "Statistical Modeling",
  "Data Governance",
  "Data Mining",
  "Data Warehousing",
  "Google Analytics",
  "A/B Testing",
  "Digital Marketing",
  "Content Strategy",
  "SEO/SEM",
  "Social Media Marketing",
  "Email Marketing",
  "Copywriting",
  "Branding",
  "Marketing Automation (HubSpot, Marketo)",
  "Graphic Design",
  "Adobe Creative Suite",
  "UX/UI Design",
  "Video Production",
  "Product Marketing",
  "Market Research",
  "Campaign Management",
  "Mechanical Engineering",
  "Electrical Engineering",
  "Civil Engineering",
  "Chemical Engineering",
  "CAD (AutoCAD, SolidWorks)",
  "Lab Techniques",
  "Quality Assurance",
  "Regulatory Compliance",
  "Biotechnology",
  "Environmental Science",
  "Process Engineering",
  "Technical Documentation",
  "Materials Science",
  "Systems Engineering",
  "Financial Analysis",
  "Financial Modeling",
  "Accounting (GAAP, IFRS)",
  "Auditing",
  "Tax Planning",
  "Budgeting",
  "Forecasting",
  "M&A Due Diligence",
  "Treasury Management",
  "ERP Systems (SAP, Oracle)",
  "Investment Management",
  "Cost Accounting",
  "Cash Flow Management",
  "Risk Analysis",
  "Bookkeeping",
  "Curriculum Development",
  "Instructional Design",
  "Adult Learning Theory",
  "E-Learning Tools",
  "Teaching",
  "Academic Research",
  "Educational Technology",
  "Student Counseling",
  "Classroom Management",
  "Learning Management Systems (LMS)",
  "Legal Research",
  "Contract Negotiation",
  "Corporate Law",
  "Intellectual Property",
  "Compliance",
  "Risk Management",
  "Employment Law",
  "Legal Writing",
  "Litigation",
  "GDPR & Data Privacy",
  "Anti-Money Laundering (AML)",
  "Patient Care",
  "Clinical Research",
  "Medical Writing",
  "Healthcare Management",
  "Telemedicine",
  "Electronic Medical Records (EMR)",
  "Nursing",
  "Medical Coding",
  "Health Informatics",
  "Epidemiology",
  "Pharmaceutical Sales",
  "HIPAA Compliance",
  "Public Health",
  "Multilingual",
  "Translation",
  "Localization",
  "International Relations",
  "Cultural Sensitivity",
  "Global Market Strategy",
  "International Law",
  "Cross-Border Negotiation",
  "Critical Thinking",
  "Decision-Making",
  "Problem-Solving",
  "Analytical Thinking",
  "Creativity",
  "Innovation",
  "Design Thinking",
  "Systems Thinking",
  "Prioritization",
  "Focus Management",
];

export default skills;
