export type TBookmark = {
  title: string;
  content: string;
  post_type: string;
  industry: string;
  visibility: string;
  experience_level: string;
  job_title: string;
  tags: string[];
  skills: string[];
  expires_at: string;
  media_url: string;
  media_type: string;
  id: string;
  user: null;
  username: null;
  is_active: true;
  created_at: string;
  updated_at: string;
  published_at: string;
  total_comments: number;
  total_reactions: number;
  is_bookmarked: boolean;
  reactions_breakdown: null;
  is_repost: boolean;
  original_post_id: string;
};
